# remote_theme: zendesk/jekyll-theme-zendesk-garden@main

# sidebar:
#  - intro
#  - label: Section One
#    children:
#      - document-one
#      - document-two
#      - document-three

theme: jekyll-theme-minimal
title: patwari ebm
description: this is just a test
